version: '3.3'

services:

  adminer:
    image: adminer
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - 9000:8080
    labels:
      - 'traefik.backend=adminer'
      - 'traefik.port=9000'

  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress

  rsync:
    user: sync
    image: instrumentisto/rsync-ssh
    volumes:
      - ~/.ssh:/sbin/.ssh
      - ./wp-content/uploads:/mnt
      - ./.docker/wp-cli:/wp-cli

  wordpress:
    image: jerturowetz/wordpress
    depends_on:
       - mysql
    restart: always
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/themes/${THEME_FOLDER:?THEME_FOLDER must be defined as an enviroment variable (or an .env file for sanity)}:/var/www/html/wp-content/themes/${THEME_FOLDER}
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_CACHE', 0 );
        define( 'WP_POST_REVISIONS', 0 );
        define( 'WP_MEMORY_LIMIT', '128M' );
        define( 'WP_MAX_MEMORY_LIMIT', '512M' );
        define( 'WP_DEBUG', 1 );
        define( 'WP_DEBUG_DISPLAY', 1 );
        define( 'WP_DEBUG_LOG', 1 );
        define( 'SCRIPT_DEBUG', 1 );
        define( 'CONCATENATE_SCRIPTS', 0 );
        define( 'JETPACK_DEV_DEBUG', 1 );
    labels:
      - "traefik.wordpress.backend=wordpress"
      - "traefik.wordpress.port=80"
      - "traefik.wordpress.frontend.rule=Host:${DEV_URL:?DEV_URL must be defined as an enviroment variable (or an .env file for sanity)}"

  wp-cli:
    image: wordpress:cli
    user: '1000:1000'
    volumes:
      - wordpress:/var/www/html
      - ./.docker/wp-cli:/var/www/html/.wp-cli
      - ./wp-content/themes/${THEME_FOLDER:?THEME_FOLDER must be defined as an enviroment variable (or an .env file for sanity)}:/var/www/html/wp-content/themes/${THEME_FOLDER}
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_PASSWORD: password
      # REPLACE_URL: "https://${PROD_URL}"
      # WITH_URL: "http://${DEV_URL}"

  composer-plugins:
    image: composer
    user: '1000:1000'
    volumes:
      - wordpress:/app
      - ./.docker/composer-plugins/plugins.json:/app/composer.json
    command: composer install

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
  wordpress:
